"""
Regression tests for Real OpenFlow 1.3 Mininet / OVS Data Plane Forwarding
"""
import pytest
import asyncio
import struct
from controller.app import SDNTrafficEngineApp
from controller.openflow.protocol import (
    OFP_VERSION,
    OFPT_PACKET_IN,
    OFPT_PACKET_OUT,
    OFPT_FLOW_MOD,
    OFPXMC_OPENFLOW_BASIC,
    OFPXMT_OFB_IN_PORT,
    ETH_TYPE_IP,
    ETH_TYPE_ARP,
    build_match,
    parse_packet_in,
    parse_ethernet,
    parse_arp,
    parse_ipv4,
    str_to_mac,
    str_to_ip,
)


def test_realistic_ovs_packet_in_wire_format():
    """
    Validates parsing of an exact OpenFlow 1.3 Packet-In message generated by Open vSwitch.
    Tests variable-length OXM match fields, match 8-byte padding, and 2-byte post-match pad.
    """
    # 1. Construct raw Ethernet + ARP frame
    src_mac = str_to_mac("00:00:00:00:00:01")
    dst_mac = str_to_mac("ff:ff:ff:ff:ff:ff")
    eth_hdr = dst_mac + src_mac + struct.pack("!H", ETH_TYPE_ARP)
    arp_body = struct.pack(
        "!HHBBH6s4s6s4s",
        1, 0x0800, 6, 4, 1,
        src_mac, str_to_ip("10.0.0.1"),
        b"\x00" * 6, str_to_ip("10.0.0.7"),
    )
    raw_frame = eth_hdr + arp_body  # 14 + 28 = 42 bytes

    # 2. Construct ofp_match with in_port = 3 (oxm_len = 8, match_len = 12, padded = 16)
    # OFPXMT_OFB_IN_PORT header: 0x80000004
    oxm_in_port = struct.pack("!II", 0x80000004, 3)
    match_hdr = struct.pack("!HH", 1, 4 + len(oxm_in_port))  # type=1, len=12
    match_pad = b"\x00" * 4  # 12 -> 16 bytes
    match_block = match_hdr + oxm_in_port + match_pad
    assert len(match_block) == 16

    # 3. Construct ofp_packet_in
    # 8-byte header: ver=4, type=10, len=8+16+16+2+42=84, xid=42
    total_msg_len = 8 + 16 + len(match_block) + 2 + len(raw_frame)
    ofp_hdr = struct.pack("!BBHI", OFP_VERSION, OFPT_PACKET_IN, total_msg_len, 42)
    # 16-byte fixed body: buffer_id=0xffffffff, total_len=42, reason=0, table_id=0, cookie=0
    ofp_body = struct.pack("!IHBBQ", 0xffffffff, len(raw_frame), 0, 0, 0)
    # 2-byte post-match pad
    post_match_pad = b"\x00\x00"

    full_packet_in_msg = ofp_hdr + ofp_body + match_block + post_match_pad + raw_frame
    assert len(full_packet_in_msg) == total_msg_len

    # 4. Parse using protocol decoder
    decoded = parse_packet_in(full_packet_in_msg)
    assert decoded is not None
    assert decoded.buffer_id == 0xffffffff
    assert decoded.total_len == len(raw_frame)
    assert decoded.in_port == 3
    assert decoded.data == raw_frame

    # 5. Verify parsed Ethernet and ARP payload matches exactly
    eth = parse_ethernet(decoded.data)
    assert eth is not None
    assert eth.src_mac == "00:00:00:00:00:01"
    assert eth.dst_mac == "ff:ff:ff:ff:ff:ff"
    assert eth.eth_type == ETH_TYPE_ARP

    arp = parse_arp(eth.payload)
    assert arp is not None
    assert arp.src_ip == "10.0.0.1"
    assert arp.dst_ip == "10.0.0.7"
    assert arp.opcode == 1


def test_origin_endpoint_resolution_from_intermediate_switch():
    """
    Verifies that when an intermediate switch (e.g. s2) emits a Packet-In for traffic
    originating from h1 (10.0.0.1) on s1, the controller correctly resolves the true
    origin endpoint and installs complete end-to-end bidirectional paths from s1 to s7.
    """
    async def run_test():
        app = SDNTrafficEngineApp()
        app.initialize_mesh_topology()

        # Create mock datapaths for s1, s2, s5, s7
        class MockDP:
            def __init__(self, sw_id, dpid):
                self.sw_id = sw_id
                self.dpid = dpid
                self.ports = {}
                self.is_active = True
                self.sent_msgs = []

            async def send_msg(self, msg: bytes) -> bool:
                self.sent_msgs.append(msg)
                return True

        dp1 = MockDP("s1", 1)
        dp2 = MockDP("s2", 2)
        dp5 = MockDP("s5", 5)
        dp7 = MockDP("s7", 7)

        app.switch_manager.datapaths[1] = dp1
        app.switch_manager.datapaths[2] = dp2
        app.switch_manager.datapaths[5] = dp5
        app.switch_manager.datapaths[7] = dp7

        # Frame from h1 (10.0.0.1) towards h7 (10.0.0.7) arriving on s2:port 1 (link from s1)
        src_mac = "00:00:00:00:00:01"
        dst_mac = "00:00:00:00:00:07"
        ip_payload = b"\x45\x00\x00\x54\x00\x01\x00\x00\x40\x01\x00\x00" + str_to_ip("10.0.0.1") + str_to_ip("10.0.0.7") + (b"\x00" * 64)
        raw_frame = str_to_mac(dst_mac) + str_to_mac(src_mac) + struct.pack("!H", ETH_TYPE_IP) + ip_payload

        # Construct Packet-In from s2 on port 1
        match_p1 = build_match(in_port=1)
        pin_hdr = struct.pack("!BBHI", OFP_VERSION, OFPT_PACKET_IN, 8 + 16 + len(match_p1) + 2 + len(raw_frame), 1)
        pin_body = struct.pack("!IHBBQ", 0xffffffff, len(raw_frame), 0, 0, 0)
        pin_msg = pin_hdr + pin_body + match_p1 + b"\x00\x00" + raw_frame

        await app.packet_handler.handle_packet_in(dp2, pin_msg)

        # 1. Verify that flow rules were installed on s1 (the true origin switch)
        assert len(dp1.sent_msgs) >= 2  # IPv4 + ARP rules for 10.0.0.7 & return
        # 2. Verify flow rules on s7 (destination switch)
        assert len(dp7.sent_msgs) >= 2
        # 3. Verify that active flows cache contains both directions
        assert any("10.0.0.7" in k and "s1" in k for k in app.flow_manager.active_flows)
        assert any("10.0.0.1" in k and "s7" in k for k in app.flow_manager.active_flows)

    asyncio.run(run_test())


def test_intra_switch_local_delivery_installs_all_rules():
    """
    Verifies that local delivery on the same switch (e.g. h7 <-> h8 on s7)
    installs all forward and reverse IPv4 and ARP rules.
    """
    async def run_test():
        app = SDNTrafficEngineApp()
        app.initialize_mesh_topology()

        class MockDP:
            def __init__(self, sw_id, dpid):
                self.sw_id = sw_id
                self.dpid = dpid
                self.ports = {}
                self.is_active = True
                self.sent_msgs = []

            async def send_msg(self, msg: bytes) -> bool:
                self.sent_msgs.append(msg)
                return True

        dp7 = MockDP("s7", 7)
        app.switch_manager.datapaths[7] = dp7

        # Frame from h7 (10.0.0.7:port 4) to h8 (10.0.0.8:port 5) on s7
        src_mac = "00:00:00:00:00:07"
        dst_mac = "00:00:00:00:00:08"
        ip_payload = b"\x45\x00\x00\x54\x00\x01\x00\x00\x40\x01\x00\x00" + str_to_ip("10.0.0.7") + str_to_ip("10.0.0.8") + (b"\x00" * 64)
        raw_frame = str_to_mac(dst_mac) + str_to_mac(src_mac) + struct.pack("!H", ETH_TYPE_IP) + ip_payload

        match_p4 = build_match(in_port=4)
        pin_hdr = struct.pack("!BBHI", OFP_VERSION, OFPT_PACKET_IN, 8 + 16 + len(match_p4) + 2 + len(raw_frame), 1)
        pin_body = struct.pack("!IHBBQ", 0xffffffff, len(raw_frame), 0, 0, 0)
        pin_msg = pin_hdr + pin_body + match_p4 + b"\x00\x00" + raw_frame

        await app.packet_handler.handle_packet_in(dp7, pin_msg)

        # Must have sent 4 flow mods (IP forward, ARP forward, IP reverse, ARP reverse) + 1 packet out
        flow_mods = [m for m in dp7.sent_msgs if m[1] == OFPT_FLOW_MOD]
        packet_outs = [m for m in dp7.sent_msgs if m[1] == OFPT_PACKET_OUT]
        assert len(flow_mods) == 4
        assert len(packet_outs) == 1

        # Check active flows dictionary for both IP and ARP entries
        assert any("10.0.0.8" in k for k in app.flow_manager.active_flows)
        assert any("10.0.0.7" in k for k in app.flow_manager.active_flows)

    asyncio.run(run_test())


def test_proactive_mesh_route_installation():
    """
    Validates that install_proactive_mesh_routes pre-programs baseline forwarding
    paths for all default mesh host pairs.
    """
    async def run_test():
        app = SDNTrafficEngineApp()
        app.initialize_mesh_topology()

        datapaths = {}
        for i in range(1, 8):
            class MockDP:
                def __init__(self, sw_id, dpid):
                    self.sw_id = sw_id
                    self.dpid = dpid
                    self.is_active = True
                    self.sent_msgs = []

                async def send_msg(self, msg: bytes) -> bool:
                    self.sent_msgs.append(msg)
                    return True

            dp = MockDP(f"s{i}", i)
            app.switch_manager.datapaths[i] = dp
            datapaths[i] = dp

        await app.packet_handler.install_proactive_mesh_routes()

        # Check that flows were installed on edge switches and intermediate switches
        assert len(datapaths[1].sent_msgs) > 0
        assert len(datapaths[7].sent_msgs) > 0
        assert len(app.flow_manager.active_flows) >= 12

    asyncio.run(run_test())
