"""OpenFlow 1.3 Protocol Definitions Stub"""

OFP_VERSION: int = 0x04

OFP_NO_BUFFER: int = 0xFFFFFFFF
OFPP_CONTROLLER: int = 0xFFFFFFFD
OFPP_FLOOD: int = 0xFFFFFFFB
OFPP_ALL: int = 0xFFFFFFFC
OFPP_ANY: int = 0xFFFFFFFF
OFPP_IN_PORT: int = 0xFFFFFFF8

OFPFC_ADD: int = 0
OFPFC_MODIFY: int = 1
OFPFC_MODIFY_STRICT: int = 2
OFPFC_DELETE: int = 3
OFPFC_DELETE_STRICT: int = 4

OFPPR_ADD: int = 0
OFPPR_DELETE: int = 1
OFPPR_MODIFY: int = 2

OFPG_ANY: int = 0xFFFFFFFF
OFPP_NORMAL: int = 0xFFFFFFFA
